const authErrors = {
    "admin-restricted-operation": "Hoạt động này chỉ được giới hạn cho quản trị viên.",
    "argument-error": "",
    "app-not-authorized": "Ứng dụng này, được xác định bởi miền nơi nó được lưu trữ, không được phép sử dụng Xác thực Firebase bằng khóa API được cung cấp. Xem lại cấu hình khóa của bạn trong bảng điều khiển API của Google.",
    "app-not-installed": "Ứng dụng di động được yêu cầu tương ứng với số nhận dạng (tên gói Android hoặc ID gói iOS) được cung cấp không được cài đặt trên thiết bị này.",
    "captcha-check-failed": "Mã phản hồi reCAPTCHA được cung cấp không hợp lệ, đã hết hạn, đã được sử dụng hoặc miền được liên kết với nó không khớp với danh sách các miền thuộc danh sách cho phép.",
    "code-expired": "Mã SMS đã hết hạn. Vui lòng gửi lại mã xác minh để thử lại.",
    "cordova-not-ready": "Khung Cordova chưa sẵn sàng.",
    "cors-unsupported": "Trình duyệt này không được hỗ trợ.",
    "credential-already-in-use": "Thông tin đăng nhập này đã được liên kết với một tài khoản người dùng khác.",
    "custom-token-mismatch": "Mã thông báo tùy chỉnh tương ứng với một đối tượng khác.",
    "requires-recent-login": "Thao tác này nhạy cảm và yêu cầu xác thực gần đây. Đăng nhập lại trước khi thử lại yêu cầu này.",
    "dynamic-link-not-activated": "Vui lòng kích hoạt Liên kết động trong Bảng điều khiển Firebase và đồng ý với các điều khoản và điều kiện.",
    "email-change-needs-verification": "Người dùng đa yếu tố phải luôn có một email đã được xác minh.",
    "email-already-in-use": "Địa chỉ email đã được một tài khoản khác sử dụng.",
    "expired-action-code": "Mã hành động đã hết hạn.",
    "cancelled-popup-request": "Thao tác này đã bị hủy do một cửa sổ bật lên xung đột khác đang được mở.",
    "internal-error": "Đã xảy ra một lỗi nội bộ.",
    "invalid-app-credential": "Yêu cầu xác minh số điện thoại chứa trình xác minh ứng dụng không hợp lệ. Phản hồi mã thông báo reCAPTCHA không hợp lệ hoặc đã hết hạn.",
    "invalid-app-id": "Mã nhận dạng ứng dụng dành cho thiết bị di động không được đăng ký cho dự án hiện tại.",
    "invalid-user-token": "Thông tin đăng nhập của người dùng này không hợp lệ cho dự án này. Điều này có thể xảy ra nếu mã thông báo của người dùng đã bị giả mạo hoặc nếu người dùng không dành cho dự án được liên kết với khóa API này.",
    "invalid-auth-event": "Đã xảy ra một lỗi nội bộ.",
    "invalid-verification-code": "Mã xác minh SMS được sử dụng để tạo thông tin xác thực điện thoại không hợp lệ. Vui lòng gửi lại sms mã xác minh và đảm bảo sử dụng mã xác minh do người dùng cung cấp.",
    "invalid-continue-uri": "The continue URL provided in the request is invalid.",
    "invalid-cordova-configuration": "The following Cordova plugins must be installed to enable OAuth sign-in: cordova-plugin-buildinfo, cordova-universal-links-plugin, cordova-plugin-browsertab, cordova-plugin-inappbrowser and cordova-plugin-customurlscheme.",
    "invalid-custom-token": "The custom token format is incorrect. Please check the documentation.",
    "invalid-dynamic-link-domain": "The provided dynamic link domain is not configured or authorized for the current project.",
    "invalid-email": "Địa chỉ email bị định dạng sai.",
    "invalid-api-key": "Your API key is invalid, please check you have copied it correctly.",
    "invalid-cert-hash": "The SHA-1 certificate hash provided is invalid.",
    "invalid-credential": "The supplied auth credential is malformed or has expired.",
    "invalid-message-payload": "The email template corresponding to this action contains invalid characters in its message. Please fix by going to the Auth email templates section in the Firebase Console.",
    "invalid-multi-factor-session": "The request does not contain a valid proof of first factor successful sign-in.",
    "invalid-oauth-provider": "EmailAuthProvider is not supported for this operation. This operation only supports OAuth providers.",
    "invalid-oauth-client-id": "The OAuth client ID provided is either invalid or does not match the specified API key.",
    "unauthorized-domain": "This domain is not authorized for OAuth operations for your Firebase project. Edit the list of authorized domains from the Firebase console.",
    "invalid-action-code": "The action code is invalid. This can happen if the code is malformed, expired, or has already been used.",
    "wrong-password": "Mật khẩu không hợp lệ hoặc người dùng không có mật khẩu.",
    "invalid-persistence-type": "The specified persistence type is invalid. It can only be local, session or none.",
    "invalid-phone-number": "The format of the phone number provided is incorrect. Please enter the phone number in a format that can be parsed into E.164 format. E.164 phone numbers are written in the format [+][country code][subscriber number including area code].",
    "invalid-provider-id": "The specified provider ID is invalid.",
    "invalid-recipient-email": "The email corresponding to this action failed to send as the provided recipient email address is invalid.",
    "invalid-sender": "Mẫu email tương ứng với hành động này chứa email hoặc tên người gửi không hợp lệ. Vui lòng khắc phục bằng cách chuyển đến phần Mẫu email xác thực trong Bảng điều khiển Firebase.",
    "invalid-verification-id": "The verification ID used to create the phone auth credential is invalid.",
    "invalid-tenant-id": "The Auth instance's tenant ID is invalid.",
    "multi-factor-info-not-found": "The user does not have a second factor matching the identifier provided.",
    "multi-factor-auth-required": "Proof of ownership of a second factor is required to complete sign-in.",
    "missing-android-pkg-name": "An Android Package Name must be provided if the Android App is required to be installed.",
    "auth-domain-config-required": "Be sure to include authDomain when calling firebase.initializeApp(), by following the instructions in the Firebase console.",
    "missing-app-credential": "The phone verification request is missing an application verifier assertion. A reCAPTCHA response token needs to be provided.",
    "missing-verification-code": "The phone auth credential was created with an empty SMS verification code.",
    "missing-continue-uri": "A continue URL must be provided in the request.",
    "missing-iframe-start": "An internal error has occurred.",
    "missing-ios-bundle-id": "An iOS Bundle ID must be provided if an App Store ID is provided.",
    "missing-multi-factor-info": "No second factor identifier is provided.",
    "missing-multi-factor-session": "The request is missing proof of first factor successful sign-in.",
    "missing-or-invalid-nonce": "The request does not contain a valid nonce. This can occur if the SHA-256 hash of the provided raw nonce does not match the hashed nonce in the ID token payload.",
    "missing-phone-number": "To send verification codes, provide a phone number for the recipient.",
    "missing-verification-id": "The phone auth credential was created with an empty verification ID.",
    "app-deleted": "This instance of FirebaseApp has been deleted.",
    "account-exists-with-different-credential": "An account already exists with the same email address but different sign-in credentials. Sign in using a provider associated with this email address.",
    "network-request-failed": "Đã xảy ra lỗi mạng (chẳng hạn như thời gian chờ, kết nối bị gián đoạn hoặc máy chủ không thể truy cập được).",
    "no-auth-event": "An internal error has occurred.",
    "no-such-provider": "User was not linked to an account with the given provider.",
    "null-user": "A null user object was provided as the argument for an operation which requires a non-null user object.",
    "operation-not-allowed": "The given sign-in provider is disabled for this Firebase project. Enable it in the Firebase console, under the sign-in method tab of the Auth section.",
    "operation-not-supported-in-this-environment": 'This operation is not supported in the environment this application is running on. "location.protocol" must be http, https or chrome-extension and web storage must be enabled.',
    "popup-blocked": "Unable to establish a connection with the popup. It may have been blocked by the browser.",
    "popup-closed-by-user": "The popup has been closed by the user before finalizing the operation.",
    "provider-already-linked": "User can only be linked to one identity for the given provider.",
    "quota-exceeded": "The project's quota for this operation has been exceeded.",
    "redirect-cancelled-by-user": "The redirect operation has been cancelled by the user before finalizing.",
    "redirect-operation-pending": "A redirect sign-in operation is already pending.",
    "rejected-credential": "The request contains malformed or mismatching credentials.",
    "second-factor-already-in-use": "The second factor is already enrolled on this account.",
    "maximum-second-factor-count-exceeded": "The maximum allowed number of second factors on a user has been exceeded.",
    "tenant-id-mismatch": "The provided tenant ID does not match the Auth instance's tenant ID",
    "timeout": "Các hoạt động đã hết thời gian.",
    "user-token-expired": "The user's credential is no longer valid. The user must sign in again.",
    "too-many-requests": "Chúng tôi đã chặn tất cả các yêu cầu từ thiết bị này do hoạt động bất thường. Thử lại sau.",
    "unauthorized-continue-uri": "The domain of the continue URL is not whitelisted.  Please whitelist the domain in the Firebase console.",
    "unsupported-first-factor": "Enrolling a second factor or signing in with a multi-factor account requires sign-in with a supported first factor.",
    "unsupported-persistence-type": "The current environment does not support the specified persistence type.",
    "unsupported-tenant-operation": "This operation is not supported in a multi-tenant context.",
    "unverified-email": "Thao tác này yêu cầu một email đã được xác minh.",
    "user-cancelled": "Người dùng đã không cấp cho ứng dụng của bạn các quyền mà nó yêu cầu.",
    "user-not-found": "Không có bản ghi người dùng tương ứng với số nhận dạng này. Người dùng có thể đã bị xóa.",
    "user-disabled": "Tài khoản người dùng đã bị vô hiệu hóa bởi quản trị viên.",
    "user-mismatch": "The supplied credentials do not correspond to the previously signed in user.",
    "user-signed-out": "",
    "weak-password": "Mật khẩu phải dài từ 6 ký tự trở lên.",
    "web-storage-unsupported": "Trình duyệt này không được hỗ trợ hoặc cookie và dữ liệu của bên thứ 3 có thể bị vô hiệu hóa."
}

export { authErrors };